import { ArrowLeft, ArrowRight, Minus, Plus, ShieldCheck, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'wouter'
import type { CartItem } from '@/types'
import { formatMeters, formatPrice, getCartTotals, orderKey } from '@/lib/catalog'

interface CartPageProps {
  cart: CartItem[]
  onUpdate: (key: string, length: number) => void
  onRemove: (key: string) => void
}

export function CartPage({ cart, onUpdate, onRemove }: CartPageProps) {
  const totals = getCartTotals(cart)
  if (cart.length === 0) return <main className="container-eva empty-state page-empty"><div className="empty-icon"><ShoppingBag size={26} /></div><h1>السلة هادئة الآن</h1><p>أضيفي قماشاً يعجبك، وستظهر تفاصيله هنا.</p><Link href="/catalog" className="button button-primary">تصفحي الأقمشة <ArrowLeft size={16} /></Link></main>
  return <main className="container-eva cart-page"><div className="breadcrumbs"><Link href="/">الرئيسية</Link><span>›</span><span>السلة</span></div><div className="page-title-row"><div><span className="eyebrow">اختياراتك</span><h1>سلة التسوق</h1><p>{formatMeters(cart.reduce((sum, item) => sum + item.length, 0))} في السلة</p></div><Link href="/catalog" className="underlined-link">متابعة التسوق <ArrowLeft size={15} /></Link></div><div className="cart-layout"><section className="cart-items" aria-label="عناصر السلة">{cart.map((item) => { const key = orderKey(item); return <article className="cart-item" key={key}><Link href={`/product/${item.product.slug}`} className="cart-item-image"><img src={item.product.image} alt={item.product.name} /></Link><div className="cart-item-info"><div className="cart-item-top"><div><span className="product-type">{item.product.type}</span><Link href={`/product/${item.product.slug}`} className="product-name">{item.product.name}</Link><span className="cart-item-color"><i style={{ backgroundColor: item.color.hex }} />{item.color.name}</span></div><button type="button" className="remove-button" onClick={() => onRemove(key)} aria-label={`حذف ${item.product.name}`}><Trash2 size={16} /></button></div><div className="cart-item-bottom"><div className="quantity-control compact"><button type="button" onClick={() => onUpdate(key, item.length - 0.5)} disabled={item.length <= 0.5} aria-label="إنقاص الكمية"><Minus size={15} /></button><output>{formatMeters(item.length)}</output><button type="button" onClick={() => onUpdate(key, item.length + 0.5)} disabled={item.length >= Math.min(item.product.stockMeters, item.color.stockMeters)} aria-label="زيادة الكمية"><Plus size={15} /></button></div><strong>{formatPrice(item.product.price * item.length)}</strong></div></div></article> })}</section><aside className="order-summary"><h2>ملخص الطلب</h2><div className="summary-line"><span>المجموع الفرعي</span><strong>{formatPrice(totals.subtotal)}</strong></div><div className="summary-line"><span>التوصيل <small>(تقديري)</small></span><strong>{totals.deliveryFee ? formatPrice(totals.deliveryFee) : 'مجاناً'}</strong></div><div className="summary-total"><span>الإجمالي</span><strong>{formatPrice(totals.total)}</strong></div><Link href="/checkout" className="button button-primary summary-button">إتمام الطلب <ArrowLeft size={16} /></Link><p className="summary-note">التوصيل متاح للعراق، ويتم احتسابه أيضاً في صفحة الدفع.</p><div className="summary-trust"><ShieldCheck size={16} /><span>سلة محفوظة على هذا الجهاز</span></div></aside></div></main>
}
