import { useState, type FormEvent } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronDown, Instagram, Mail, MessageCircle, PackageCheck, Phone, Search, Send, Sparkles, Truck } from 'lucide-react'
import { Link, useLocation } from 'wouter'
import { guideQuestions } from '@/lib/fallback-data'
import { siteConfig } from '@/lib/site'

export function AboutPage() {
  return <main className="container-eva info-page"><div className="breadcrumbs"><Link href="/">الرئيسية</Link><span>›</span><span>من نحن</span></div><section className="about-hero"><div className="about-copy"><span className="eyebrow"><Sparkles size={14} />من إيفا إلى يدك</span><h1>مساحة تساعدك على اختيار القماش بثقة.</h1><p>في إيفا ستور نؤمن أن الخامة الجيدة تبدأ بسؤال واضح: ما الذي ستصنعينه؟ لذلك نعرض تفاصيل واقعية، ونشرح المرونة والشفافية والعناية قبل أن تطلبي.</p><div className="about-points"><div><span>01</span><strong>وضوح قبل الطلب</strong><p>مواصفات وخطوات طلب بنصف متر.</p></div><div><span>02</span><strong>اختيار أهدأ</strong><p>صور وتفاصيل تساعدك على المقارنة.</p></div><div><span>03</span><strong>دعم قريب</strong><p>تواصلي معنا قبل وبعد الطلب.</p></div></div></div><div className="about-collage"><img src="fabrics/rose.jpg" alt="قماش مطرز من معرض إيفا" /><img src="fabrics/blue.jpg" alt="قماش أزرق ناعم" /><span>EVA<br /><strong>FABRICS</strong></span></div></section><section className="story-band"><span>من الفكرة إلى القطعة</span><h2>نؤمن أن التفاصيل الصغيرة تصنع الفرق.</h2><p>من ترتيب العرض إلى طريقة تعبئة الطلب، نبني تجربة تحترم وقتك وتمنحك مساحة لتسأل قبل أن تقرر.</p></section></main>
}

export function FabricGuidePage() {
  return <main className="container-eva info-page"><div className="breadcrumbs"><Link href="/">الرئيسية</Link><span>›</span><span>دليل الأقمشة</span></div><section className="info-heading"><span className="eyebrow">تعلمي قبل أن تختاري</span><h1>دليل الأقمشة</h1><p>كل خامة لها إيقاعها. اقرئي هذه الإجابات السريعة، ثم افتحي صفحة المنتج لتفاصيل أكثر.</p></section><section className="guide-grid">{guideQuestions.map((item, index) => <details className="guide-card" key={item.question} open={index === 0}><summary><span>٠{index + 1}</span><strong>{item.question}</strong><ChevronDown size={18} /></summary><p>{item.answer}</p></details>)}</section><section className="guide-steps"><div><span>١</span><strong>حددي الاستخدام</strong><p>فستان يومي، سهرة، عباءة أو قطعة عملية؟</p></div><div><span>٢</span><strong>قارني الخامة</strong><p>الوزن، العرض، المرونة، الشفافية والتشطيب.</p></div><div><span>٣</span><strong>احسبي الكمية</strong><p>أضيفي هامشاً للقص والخياطة، ثم اطلبي نصفي متر.</p></div></section><div className="center-action"><Link href="/catalog" className="button button-primary">ابدئي من المعرض <ArrowLeft size={16} /></Link></div></main>
}

export function ContactPage() {
  const [name, setName] = useState('')
  const [message, setMessage] = useState('')
  const [email, setEmail] = useState('')
  const openWhatsApp = (event: FormEvent) => {
    event.preventDefault()
    const text = `مرحباً إيفا ستور، أنا ${name || 'زائرة'}${email ? ` (${email})` : ''}. ${message}`
    window.open(siteConfig.whatsappUrl(text), '_blank', 'noopener,noreferrer')
  }
  return <main className="container-eva info-page"><div className="breadcrumbs"><Link href="/">الرئيسية</Link><span>›</span><span>تواصلي معنا</span></div><section className="contact-layout"><div className="contact-intro"><span className="eyebrow">نحن قريبون</span><h1>سؤال عن خامة أو طلب؟</h1><p>اكتبي لنا ما يدور في بالك، وسنحوّلك إلى محادثة واتساب لتتواصلي مباشرة مع الفريق.</p><div className="contact-methods"><a href={siteConfig.whatsappUrl()} target="_blank" rel="noreferrer"><MessageCircle size={19} /><span><strong>واتساب</strong><small dir="ltr">{siteConfig.phone}</small></span><ArrowLeft size={15} /></a><a href={`tel:${siteConfig.phone}`}><Phone size={19} /><span><strong>اتصال هاتفي</strong><small dir="ltr">{siteConfig.phone}</small></span><ArrowLeft size={15} /></a><a href={siteConfig.instagramUrl} target="_blank" rel="noreferrer"><Instagram size={19} /><span><strong>إنستغرام</strong><small>راسلينا أو شاهدي أحدث القطع</small></span><ArrowLeft size={15} /></a></div></div><form className="contact-form soft-card" onSubmit={openWhatsApp}><div className="form-fields"><div className="field"><label htmlFor="contact-name">اسمك <small>(اختياري)</small></label><div className="field-input"><Sparkles size={17} /><input id="contact-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="كيف نناديك؟" /></div></div><div className="field"><label htmlFor="contact-email">البريد الإلكتروني <small>(اختياري)</small></label><div className="field-input"><Mail size={17} /><input id="contact-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="example@email.com" /></div></div><div className="field"><label htmlFor="contact-message">رسالتك</label><textarea id="contact-message" rows={6} value={message} onChange={(event) => setMessage(event.target.value)} placeholder="اكتبي سؤالك أو نوع الخامة التي تبحثين عنها" required /></div></div><button type="submit" className="button button-primary"><Send size={16} />فتح محادثة واتساب</button><p className="form-footnote">لن تُرسل الرسالة تلقائياً؛ ستنتقلين إلى واتساب لتراجعيها قبل الإرسال.</p></form></section></main>
}

export function PoliciesPage() {
  return <main className="container-eva info-page policies-page"><div className="breadcrumbs"><Link href="/">الرئيسية</Link><span>›</span><span>السياسات</span></div><section className="info-heading"><span className="eyebrow">واضحة منذ البداية</span><h1>سياسات المتجر</h1><p>اقرأ هذه البنود قبل إتمام الطلب، وتواصلي معنا إذا كان لديك استفسار.</p></section><div className="policy-nav"><a href="#terms">شروط الاستخدام</a><a href="#privacy">الخصوصية</a><a href="#shipping">الشحن</a><a href="#returns">الإرجاع</a></div><div className="policy-list"><PolicySection id="terms" title="شروط الاستخدام" content="باستخدامك موقع إيفا ستور، فإنك تقرين بصحة المعلومات المدخلة وأنك تستخدمين الموقع لطلب المنتجات المتاحة. الأسعار والألوان قابلة للتحديث، ويظهر السعر النهائي قبل التأكيد." /><PolicySection id="privacy" title="سياسة الخصوصية" content="نستخدم البيانات التي تدخلينها لإتمام الطلب والتواصل معك بشأنه فقط. لا نشارك بياناتك مع جهات غير ضرورية، ويمكنك طلب تحديثها أو حذفها بالتواصل معنا." /><PolicySection id="shipping" title="الشحن والتوصيل" content="نجهز الطلبات بعد التأكيد، ويظهر رقم الطلب في صفحة النجاح. يختلف وقت الوصول بحسب المحافظة وحالة الطلب، ويتم تحديثك من خلال واتساب عند الحاجة." /><PolicySection id="returns" title="الإرجاع والتبديل" content="تواصلي معنا خلال 48 ساعة من الاستلام إذا وصل القماش مختلفاً أو حدث خطأ في الطلب. تعتمد إمكانية الإرجاع على حالة القطعة وطريقة الاستخدام، ويؤكد الفريق التفاصيل معك." /></div></main>
}

export function OrderTrackingPage() {
  const [location, navigate] = useLocation()
  const query = new URLSearchParams(location.includes('?') ? location.slice(location.indexOf('?') + 1) : '')
  const currentOrder = query.get('order') || ''
  const [orderNumber, setOrderNumber] = useState(currentOrder)
  const submit = (event: FormEvent) => { event.preventDefault(); const clean = orderNumber.trim(); if (clean) navigate(`/order-tracking?order=${encodeURIComponent(clean)}`) }
  return <main className="container-eva info-page"><div className="breadcrumbs"><Link href="/">الرئيسية</Link><span>›</span><span>تتبع الطلب</span></div><section className="tracking-card"><div className="tracking-icon"><PackageCheck size={28} /></div><span className="eyebrow">تحديث رحلتك</span><h1>تتبّع الطلب</h1><p>أدخلي رقم الطلب الذي استلمته بعد التأكيد. يمكنك أيضاً سؤال فريقنا عن آخر تحديث عبر واتساب.</p><form className="tracking-form" onSubmit={submit}><label className="sr-only" htmlFor="tracking-order">رقم الطلب</label><Search size={18} /><input id="tracking-order" value={orderNumber} onChange={(event) => setOrderNumber(event.target.value)} placeholder="مثال: EVA-1024" dir="ltr" /><button type="submit" className="button button-primary">عرض الرقم</button></form>{currentOrder && <div className="tracking-result" role="status"><Check size={18} /><div><strong>رقم الطلب الذي أدخلته: {currentOrder}</strong><p>حالة التحديث النهائية تُرسل عبر واتساب أو من فريق الخدمة. لا يظهر هنا افتراضياً حتى يصل تحديث من الخادم.</p></div></div>}<a href={siteConfig.whatsappUrl(`مرحباً، أريد الاستفسار عن الطلب رقم ${currentOrder || ''}`)} target="_blank" rel="noreferrer" className="button button-outline"><MessageCircle size={16} />اسألينا عبر واتساب</a></section></main>
}

export function OrderConfirmationPage({ orderNumber }: { orderNumber: string }) {
  return <main className="container-eva confirmation-page"><div className="confirmation-mark"><Check size={30} /></div><span className="eyebrow">تم استلام طلبك</span><h1>شكراً لاختيارك إيفا.</h1><p>سنراجع تفاصيل طلبك ونتواصل معك لتأكيد موعد التوصيل.</p><div className="confirmation-number"><small>رقم الطلب</small><strong dir="ltr">{orderNumber}</strong></div><div className="confirmation-actions"><Link href="/catalog" className="button button-primary">متابعة التسوق <ArrowLeft size={16} /></Link><a href={siteConfig.whatsappUrl(`مرحباً، أستفسر عن الطلب رقم ${orderNumber}`)} target="_blank" rel="noreferrer" className="button button-outline"><MessageCircle size={16} />تواصلي عبر واتساب</a></div><div className="confirmation-trust"><Truck size={17} /><span>سنرسل رقم الطلب وتفاصيل الشحن عند تأكيد الطلب.</span></div></main>
}

function PolicySection({ id, title, content }: { id: string; title: string; content: string }) { return <section className="policy-section" id={id}><h2>{title}</h2><p>{content}</p></section> }
